/**:
  pi_camera:
    ros__parameters:
      pipeline: >-
        libcamerasrc !
        video/x-raw,width=1280,height=720,framerate=30/1 !
        videoconvert !
        v4l2h264enc extra-controls="controls,video_bitrate=3000000,h264_i_frame_period=30" !
        video/x-h264,level=(string)4,profile=main !
        h264parse config-interval=1 !
        queue max-size-buffers=100 !
        rtspclientsink location=rtsp://localhost:8554/cam1

  usb_camera:
    ros__parameters:
      pipeline: >-
        v4l2src device=/dev/video4 !
        video/x-h264,width=1280,height=720,framerate=30/1 !
        h264parse config-interval=1 !
        queue max-size-buffers=100 !
        rtspclientsink location=rtsp://localhost:8554/cam2
