/**:
  controller_manager:
    ros__parameters:
      update_rate: 300 # Hz

  gate_controller:
    ros__parameters:
      type: sinsei_umiusi_control/controller/GateController
      update_rate: 50 # Hz

  app_controller:
    ros__parameters:
      type: sinsei_umiusi_control/controller/AppController
      update_rate: 50 # Hz

  thruster_controller_lf: # Left Front Thruster
    ros__parameters:
      type: sinsei_umiusi_control/controller/ThrusterController
      update_rate: 50 # Hz
      id: 1

  thruster_controller_lb: # Left Back Thruster
    ros__parameters:
      type: sinsei_umiusi_control/controller/ThrusterController
      update_rate: 50 # Hz
      id: 2

  thruster_controller_rb: # Right Back Thruster
    ros__parameters:
      type: sinsei_umiusi_control/controller/ThrusterController
      update_rate: 50 # Hz
      id: 3

  thruster_controller_rf: # Right Front Thruster
    ros__parameters:
      type: sinsei_umiusi_control/controller/ThrusterController
      update_rate: 50 # Hz
      id: 4
