codecov:
  notify:
    wait_for_ci: false

coverage:
  range: "50...70"

component_management:
  default_rules:
    statuses:
      - type: project
        target: 60%
        threshold: 15%
      - type: patch
        informational: true
  individual_components:
    - component_id: hardware_interfaces
      name: Hardware interfaces (ROS2 control)
      paths:
        - "**/hardware/*"
        - "**/hardware/**/*"
      statuses:
        - type: project
          informational: true
    - component_id: hardware_impls
      name: Hardware implementations
      paths:
        - "**/hardware_model/impl/*"
        - "**/hardware_model/impl/**/*"
      statuses:
        - type: project
          informational: true
    - component_id: core
      name: Core logic
      paths:
        - "!**/hardware/*"
        - "!**/hardware/**/*"
        - "!**/hardware_model/impl/*"
        - "!**/hardware_model/impl/**/*"

comment:
  layout: "files, components"
  hide_project_coverage: false
  behavior: once

fixes:
  - "ros_ws/src/*/sinsei_UMIUSI_control/sinsei_umiusi_control/::"

github_checks:
  annotations: false
