codecov:
  notify:
    wait_for_ci: false

component_management:
  default_rules:
    statuses:
      - type: project
        range: "60...70"
        target: 60%
        threshold: 15%
      - type: patch
        informational: true
  individual_components:
    - component_id: hardware_interfaces
      name: hardware_interfaces
      paths:
        - "(src|include)/**/hardware/**"
      statuses:
        - type: project
          informational: true
    - component_id: core
      name: core
      paths:
        - "!((src|include)/**/hardware|(src|include)/**/hardware_model/impl)/**"

comment:
  layout: "diff, components"
  hide_project_coverage: false
  behavior: once

fixes:
  - "ros_ws/src/*/sinsei_UMIUSI_control/sinsei_umiusi_control/::"

github_checks:
  annotations: false
