codecov:
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 15%
    patch:
      default:
        informational: true

comment:
  layout: "diff, files"
  hide_project_coverage: false
  behavior: once

fixes:
  - "ros_ws/src/*/sinsei_UMIUSI_control/sinsei_umiusi_control/::"

github_checks:
  annotations: false
