#ifndef SINSEI_UMIUSI_CONTROL_CONTROLLER_LOGIC_ATTITUDE_FEED_FORWARD_HPP
#define SINSEI_UMIUSI_CONTROL_CONTROLLER_LOGIC_ATTITUDE_FEED_FORWARD_HPP

#include <Eigen/Core>
#include <Eigen/LU>
#include <algorithm>
#include <array>
#include <boost/math/constants/constants.hpp>
#include <optional>
#include <stdexcept>

#include "sinsei_umiusi_control/controller/attitude_controller.hpp"
#include "sinsei_umiusi_control/controller/logic/attitude/data_conversion.hpp"

namespace sinsei_umiusi_control::controller::logic::attitude {

class FeedForward : public AttitudeController::Logic {
  private:
    using AllocationMatrix = Eigen::Matrix<double, 8, 6>;

    AllocationMatrix allocation_matrix;

    static auto healthy_allocation_matrix() -> AllocationMatrix {
        const auto sqrt_two = boost::math::constants::root_two<double>();
        return AllocationMatrix{
            {0.0, 0.0, 1.0, -sqrt_two, sqrt_two, 0.0},  {1.0, -1.0, 0.0, 0.0, 0.0, 1.0},
            {0.0, 0.0, 1.0, -sqrt_two, -sqrt_two, 0.0}, {1.0, 1.0, 0.0, 0.0, 0.0, 1.0},
            {0.0, 0.0, 1.0, sqrt_two, -sqrt_two, 0.0},  {-1.0, 1.0, 0.0, 0.0, 0.0, 1.0},
            {0.0, 0.0, 1.0, sqrt_two, sqrt_two, 0.0},   {-1.0, -1.0, 0.0, 0.0, 0.0, 1.0},
        };
    }

    static auto make_allocation_matrix(const std::optional<size_t> disabled_thruster)
        -> AllocationMatrix {
        const auto healthy_allocation = healthy_allocation_matrix();
        if (!disabled_thruster) {
            return healthy_allocation;
        }
        if (disabled_thruster.value() >= 4) {
            throw std::invalid_argument("disabled_thruster index must be less than 4");
        }

        // Recover the vehicle command generated by the healthy allocation, then invert the
        // remaining six actuator components. This preserves all six commanded degrees of freedom
        // while forcing both components of the failed thruster to zero.
        const Eigen::Matrix<double, 6, 8> components_to_command =
            (healthy_allocation.transpose() * healthy_allocation).inverse() *
            healthy_allocation.transpose();
        auto remaining_components_to_command = Eigen::Matrix<double, 6, 6>{};
        auto remaining_component_indices = std::array<size_t, 6>{};
        auto remaining_index = size_t{0};
        for (auto component_index = size_t{0}; component_index < 8; ++component_index) {
            if (component_index / 2 == disabled_thruster.value()) {
                continue;
            }
            remaining_components_to_command.col(remaining_index) =
                components_to_command.col(component_index);
            remaining_component_indices[remaining_index] = component_index;
            ++remaining_index;
        }

        AllocationMatrix allocation = AllocationMatrix::Zero();
        const Eigen::Matrix<double, 6, 6> remaining_allocation =
            remaining_components_to_command.inverse();
        for (auto i = size_t{0}; i < remaining_component_indices.size(); ++i) {
            allocation.row(remaining_component_indices[i]) = remaining_allocation.row(i);
        }
        return allocation;
    }

    static auto atan_or_zero(const double & x, const double & y) -> double {
        constexpr auto pi = boost::math::constants::pi<double>();
        if (x == 0.0 && y == 0.0) {
            return 0.0;
        }
        return std::atan(y / x) * 180.0 / pi;
    }

    static auto magnitude(const double & x, const double & y) -> double {
        return std::sqrt(x * x + y * y);
    }

    static auto sign(const double & x) -> double { return x < 0.0 ? -1.0 : 1.0; }

  public:
    explicit FeedForward(const std::optional<size_t> disabled_thruster = std::nullopt)
    : allocation_matrix(make_allocation_matrix(disabled_thruster)) {}

    auto control_mode() const -> logic::ControlMode override {
        return logic::ControlMode::FeedForward;
    }

    auto init(
        double /*time*/, const AttitudeController::Input & /*input*/,
        const AttitudeController::Output & output) -> AttitudeController::Output override {
        return output;
    }

    auto update(double /*time*/, double /*duration*/, const AttitudeController::Input & input)
        -> AttitudeController::Output override {
        const auto target_orientation = to_eigen_vector(input.cmd.target_orientation);
        const auto target_velocity = to_eigen_vector(input.cmd.target_velocity);

        // θx, θy, θz, vx, vy, vz
        //  -> f1h, f1v, f2h, f2v, f3h, f3v, f4h, f4v (h: horizontal, v: vertical)
        // z軸まわりに半時計周りをfの番号順とhorizontalの正の方向とする

        // 変換前の行列
        const auto u = Eigen::Vector<double, 6>{
            target_orientation[0],  // 目標姿勢ベクトル
            target_orientation[1],  //
            target_orientation[2],  //
            target_velocity[0],     // 目標速度ベクトル
            target_velocity[1],     //
            target_velocity[2],     //
        };
        const auto y = this->allocation_matrix * u;

        auto output = AttitudeController::Output{};
        output.cmd.servo_angles = {
            sinsei_umiusi_control::cmd::thruster::servo::Angle{atan_or_zero(y[0], y[1])},
            sinsei_umiusi_control::cmd::thruster::servo::Angle{atan_or_zero(y[2], y[3])},
            sinsei_umiusi_control::cmd::thruster::servo::Angle{atan_or_zero(y[4], y[5])},
            sinsei_umiusi_control::cmd::thruster::servo::Angle{atan_or_zero(y[6], y[7])},
        };
        const auto thrust_sgns =
            std::array<double, 4>{sign(y[0]), sign(y[2]), sign(y[4]), sign(y[6])};
        const auto thrust_abss = std::array<double, 4>{
            magnitude(y[0], y[1]), magnitude(y[2], y[3]), magnitude(y[4], y[5]),
            magnitude(y[6], y[7])};

        // The three-thruster allocation can require more output than the healthy allocation.
        // Scale every thruster uniformly when necessary so the requested wrench direction is
        // preserved instead of allowing per-thruster clipping to distort it.
        constexpr auto MAX_THRUST = boost::math::constants::root_two<double>();
        const auto normalization =
            std::max(MAX_THRUST, *std::max_element(thrust_abss.begin(), thrust_abss.end()));
        output.cmd.esc_thrusts = {
            sinsei_umiusi_control::cmd::thruster::esc::Thrust{
                thrust_sgns[0] * thrust_abss[0] / normalization},
            sinsei_umiusi_control::cmd::thruster::esc::Thrust{
                thrust_sgns[1] * thrust_abss[1] / normalization},
            sinsei_umiusi_control::cmd::thruster::esc::Thrust{
                thrust_sgns[2] * thrust_abss[2] / normalization},
            sinsei_umiusi_control::cmd::thruster::esc::Thrust{
                thrust_sgns[3] * thrust_abss[3] / normalization},
        };

        return output;
    }
};

}  // namespace sinsei_umiusi_control::controller::logic::attitude

#endif  // SINSEI_UMIUSI_CONTROL_CONTROLLER_LOGIC_ATTITUDE_FEED_FORWARD_HPP
