# see: https://github.com/marketplace/actions/ros-2-ci-action

name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  colcon-test:
    runs-on: ubuntu-latest
    outputs:
      pkg-name: sinsei_umiusi_control
      ros-distro: ${{ steps.set-ros-distro.outputs.ROS_DISTRO }}
      ws-name: ${{ steps.build.outputs.ros-workspace-directory-name }}
    steps:
      - name: Set ROS Distro
        id: set-ros-distro
        run: echo "ROS_DISTRO=jazzy" >> $GITHUB_OUTPUT

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-packages: ${{ steps.set-ros-distro.outputs.ROS_DISTRO }}
      - run: |
          source /opt/ros/jazzy/setup.bash && \
          rosdep init && rosdep update && rosdep install --from-paths src --ignore-src -y
      - run: |
          sudo apt-get update && sudo apt-get install -y \
            ninja-build

      - name: Colcon Build & Test
        id: build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ steps.set-ros-distro.outputs.ROS_DISTRO }}
          rosdep-check: true
          colcon-defaults: |
            {
              "build": {
                "cmake-args": ["-G Ninja"]
              }
            }

      - uses: actions/upload-artifact@v4
        with:
          name: ros-includes
          path: /opt/ros/${{ steps.set-ros-distro.outputs.ROS_DISTRO }}/include
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ steps.build.outputs.ros-workspace-directory-name }}/build
      - uses: actions/upload-artifact@v4
        with:
          name: log
          path: ${{ steps.build.outputs.ros-workspace-directory-name }}/log

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/ruff-action@v3

      - name: Ruff Check
        run: ruff check

      - name: Ruff Format
        run: ruff format --check --diff

  cpp-lint:
    needs: colcon-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ros-includes
          path: /opt/ros/${{ needs.colcon-test.outputs.ros-distro }}/include
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/${{ needs.colcon-test.outputs.ws-path }}/build
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/${{ needs.colcon-test.outputs.ws-path }}/sinsei_umiusi_control

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          update-environment: false

      - name: Clang-format & Clang-tidy Check
        uses: cpp-linter/cpp-linter-action@v2
        id: lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          base_dir: ${{ needs.colcon-test.outputs.ws-path }}
          tidy-checks: ""
          files-changed-only: false # プロジェクトが安定してきたらtrueにする
          thread-comments: true
          step-summary: true
      - name: on fail
        if: steps.lint.outputs.checks-failed > 0
        run: exit 1
