# see: https://github.com/marketplace/actions/ros-2-ci-action

name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/ruff-action@v3

      - name: Ruff Format
        run: ruff format --check --diff
        continue-on-error: true

      - name: Ruff check
        run: ruff check

  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    steps:
      - name: Build and Run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          rosdep-check: true
