# see: https://github.com/marketplace/actions/ros-2-ci-action

name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  colcon-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    outputs:
      ws-path: ${{ steps.build.outputs.ros-workspace-directory-name }}
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y \
            ninja-build

      - name: Colcon Build & Test
        id: build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          rosdep-check: true
          colcon-defaults: |
            {
              "build": {
                "mixin": ["ninja", "compile-commands"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ steps.build.outputs.ros-workspace-directory-name }}/build
      - uses: actions/upload-artifact@v4
        with:
          name: log
          path: ${{ steps.build.outputs.ros-workspace-directory-name }}/log

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/ruff-action@v3

      - name: Ruff Check
        run: ruff check

      - name: Ruff Format
        run: ruff format --check --diff

  cpp-lint:
    needs: colcon-test
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ${{ needs.colcon-test.outputs.ws-path }}
          pattern: build
          merge-multiple: true
      - uses: cpp-linter/cpp-linter-action@v2
        id: lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: Fail fast
        if: steps.lint.outputs.checks-failed > 0
        run: exit 1
