name: Main CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  parse-env-file:
    name: Parse Environment
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_NAME: ${{ steps.parse-env-file.outputs.PACKAGE_NAME }}
      ROS_DISTRO: ${{ steps.parse-env-file.outputs.ROS_DISTRO }}
      file-hash: ${{ steps.hash-files.outputs.hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse environment file
        id: parse-env-file
        shell: bash
        run: source .github/workflows/scripts/parse-env-file.sh $GITHUB_OUTPUT || exit 0

      - name: Hash files for cache key
        id: hash-files
        run: echo "hash=${{ hashFiles('**/*.cpp', '**/*.hpp', '**/*.py') }}" >> "$GITHUB_OUTPUT"

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: Ruff Check
        run: ruff check

      - name: Ruff Format
        run: ruff format --check --diff

  editorconfig-check:
    name: EditorConfig Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 最近のバージョンのタグがないためコミットIDを指定
      - uses: editorconfig-checker/action-editorconfig-checker@48920075d6a466d902d683b648b6365703e49293

      - name: EditorConfig Check
        run: editorconfig-checker

  colcon-build:
    name: Colcon Build
    needs: parse-env-file
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest

    steps:
      - name: Checkout install script
        uses: actions/checkout@v4
        with:
          sparse-checkout: .docker/scripts

      - name: Install can-utils
        run: sudo apt-get install -y can-utils

      - name: Install pigpio
        run: chmod +x ./.docker/scripts/install-pigpio.sh && sudo ./.docker/scripts/install-pigpio.sh

      - name: Fetch cache
        uses: actions/cache@v4
        env:
          prefix: ${{ runner.os }}-sccache-ros-${{ needs.parse-env-file.outputs.ROS_DISTRO }}-build
        with:
          path: /github/home/.cache/sccache
          key: ${{ env.prefix }}-${{ needs.parse-env-file.outputs.file-hash }}
          restore-keys: ${{ env.prefix }}-

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: "v0.7.7" # sccache version as apt package

      - name: Colcon Build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ needs.parse-env-file.outputs.ROS_DISTRO }}
          package-name: "${{ needs.parse-env-file.outputs.PACKAGE_NAME }} sinsei_umiusi_msgs"
          vcs-repo-file-url: ./deps.repos
          skip-tests: true
          coverage-result: false
          no-symlink-install: true

      - name: Upload ROS C++ libraries
        uses: actions/upload-artifact@v4
        with:
          name: ros-cpp-libraries
          path: |
            /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}/include
            /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}/src

      - name: Archive build and install artifacts
        shell: bash
        run: tar -czf build-artifacts.tar.gz -C ros_ws build install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz
          if-no-files-found: error

  cpp-lint:
    name: C++ Lint
    needs: [parse-env-file, colcon-build]
    runs-on: ubuntu-latest
    env:
      SED_ARG: s|/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ros_ws|${{ github.workspace }}/ros_ws|g
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ros_ws/src/${{ github.event.repository.name }}

      - name: Install can-utils
        run: sudo apt-get install -y can-utils

      - name: Install pigpio
        run: chmod +x ./.docker/scripts/install-pigpio.sh && sudo ./.docker/scripts/install-pigpio.sh

      - name: Download ROS C++ libraries
        uses: actions/download-artifact@v4
        with:
          name: ros-cpp-libraries
          path: /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}
          merge-multiple: true

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Extract Build Artifacts
        shell: bash
        run: tar -xzf build-artifacts.tar.gz -C ros_ws

      - name: Replace paths in compile_commands.json
        run: |
          sed -i "${{ env.SED_ARG }}" ros_ws/build/compile_commands.json
          echo "Replaced ROS working directory in compile_commands.json" && cat build/compile_commands.json

      - name: C++ Lint
        id: cpp-lint
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          verbosity: debug
          version: 18
          style: file
          tidy-checks: ""
          database: ros_ws/build
          ignore: "ros_ws/build|ros_ws/install|.github"
          step-summary: true
          files-changed-only: false

      - name: On failed
        if: steps.cpp-lint.outputs.checks-failed > 0
        run: echo "C++ lint checks failed ... ${{ steps.cpp-lint.outputs.checks-failed }}" && exit 1

  colcon-test:
    name: Colcon Test
    needs: [parse-env-file, colcon-build]
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ros_ws/src/${{ github.event.repository.name }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Extract Build Artifacts
        shell: bash
        run: tar -xzf build-artifacts.tar.gz -C ros_ws

      - name: Run Colcon Test
        working-directory: ros_ws
        shell: bash
        run: |
          source /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}/setup.bash
          source install/setup.bash
          colcon test \
            --event-handlers=console_direct+ \
            --packages-select ${{ needs.parse-env-file.outputs.PACKAGE_NAME }} sinsei_umiusi_msgs

      - name: Show Colcon Test Result
        if: always()
        working-directory: ros_ws
        shell: bash
        run: |
          source /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}/setup.bash
          source install/setup.bash
          colcon test-result --all --verbose
