name: Main CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

permissions:
  contents: read
  packages: read

jobs:
  parse-env-file:
    name: Parse Environment
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_NAME: ${{ steps.parse-env-file.outputs.PACKAGE_NAME }}
      ROS_DISTRO: ${{ steps.parse-env-file.outputs.ROS_DISTRO }}
      file-hash: ${{ steps.hash-files.outputs.hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse environment file
        id: parse-env-file
        shell: bash
        run: source .github/workflows/scripts/parse-env-file.sh $GITHUB_OUTPUT || exit 0

      - name: Hash files for cache key
        id: hash-files
        run: echo "hash=${{ hashFiles('**/*.cpp', '**/*.hpp', '**/*.py') }}" >> "$GITHUB_OUTPUT"

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: Ruff Check
        run: ruff check

      - name: Ruff Format
        run: ruff format --check --diff

  editorconfig-check:
    name: EditorConfig Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 最近のバージョンのタグがないためコミットIDを指定
      - uses: editorconfig-checker/action-editorconfig-checker@48920075d6a466d902d683b648b6365703e49293

      - name: EditorConfig Check
        run: editorconfig-checker

  colcon-build:
    name: Colcon Build
    needs: parse-env-file
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rogy-aqualab/sinsei_umiusi_control:${{ needs.parse-env-file.outputs.ROS_DISTRO }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch cache
        uses: actions/cache@v4
        env:
          prefix: ${{ runner.os }}-sccache-ros-${{ needs.parse-env-file.outputs.ROS_DISTRO }}-ci
        with:
          path: /github/home/.cache/sccache
          key: ${{ env.prefix }}-${{ needs.parse-env-file.outputs.file-hash }}
          restore-keys: ${{ env.prefix }}-

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: "v0.7.7" # sccache version as apt package

      - name: Prepare ROS workspace
        run: |
          rm -rf /home/ubuntu/ros_ws/src/pkg
          ln -s "$GITHUB_WORKSPACE" /home/ubuntu/ros_ws/src/pkg

      - name: Colcon Build
        working-directory: /home/ubuntu/ros_ws
        shell: bash
        run: |
          source /opt/ros/${{ needs.parse-env-file.outputs.ROS_DISTRO }}/setup.bash
          colcon build \
            --packages-up-to "${{ needs.parse-env-file.outputs.PACKAGE_NAME }}" \
            --symlink-install \
            --event-handlers console_direct+

      - name: Upload Build results (`build` directory)
        uses: actions/upload-artifact@v4
        with:
          name: colcon-build-results-build
          path: /home/ubuntu/ros_ws/build

      - name: Upload Build results (`install` directory)
        uses: actions/upload-artifact@v4
        with:
          name: colcon-build-results-install
          path: /home/ubuntu/ros_ws/install

  cpp-lint:
    name: C++ Lint
    needs: [parse-env-file, colcon-build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rogy-aqualab/sinsei_umiusi_control:${{ needs.parse-env-file.outputs.ROS_DISTRO }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build results (`build` directory)
        uses: actions/download-artifact@v4
        with:
          name: colcon-build-results-build
          path: /home/ubuntu/ros_ws/build

      - name: Download Build results (`install` directory)
        uses: actions/download-artifact@v4
        with:
          name: colcon-build-results-install
          path: /home/ubuntu/ros_ws/install

      - name: Prepare ROS workspace
        run: |
          rm -rf /home/ubuntu/ros_ws/src/pkg
          ln -s "$GITHUB_WORKSPACE" /home/ubuntu/ros_ws/src/pkg

      - name: Rewrite compile_commands.json paths
        run: |
          if [ -f /home/ubuntu/ros_ws/build/compile_commands.json ]; then
            sed -i "s|/home/ubuntu/ros_ws/src/pkg|$GITHUB_WORKSPACE|g" /home/ubuntu/ros_ws/build/compile_commands.json
            echo "Fixed working directory paths in compile_commands.json"
          fi

      - name: C++ Lint
        id: cpp-lint
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          verbosity: debug
          version: 18
          style: file
          tidy-checks: ""
          database: /home/ubuntu/ros_ws/build
          ignore: ./.github | ./build
          step-summary: true
          files-changed-only: false

      - name: Check C++ Lint result
        if: steps.cpp-lint.outputs.checks-failed > 0
        run: echo "C++ lint checks failed ... ${{ steps.cpp-lint.outputs.checks-failed }}" && exit 1

  colcon-test:
    name: Colcon Test
    needs: [parse-env-file, colcon-build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rogy-aqualab/sinsei_umiusi_control:${{ needs.parse-env-file.outputs.ROS_DISTRO }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build results (`build` directory)
        uses: actions/download-artifact@v4
        with:
          name: colcon-build-results-build
          path: /home/ubuntu/ros_ws/build

      - name: Download Build results (`install` directory)
        uses: actions/download-artifact@v4
        with:
          name: colcon-build-results-install
          path: /home/ubuntu/ros_ws/install

      - name: Prepare ROS workspace
        run: |
          rm -rf /home/ubuntu/ros_ws/src/pkg
          ln -s "$GITHUB_WORKSPACE" /home/ubuntu/ros_ws/src/pkg

      - name: Colcon Test
        working-directory: /home/ubuntu/ros_ws
        shell: bash
        run: |
          source /home/ubuntu/ros_ws/install/setup.bash
          colcon test \
            --packages-select "${{ needs.parse-env-file.outputs.PACKAGE_NAME }}" \
            --event-handlers console_direct+

      - name: Colcon Test Result
        working-directory: /home/ubuntu/ros_ws
        if: always()
        run: colcon test-result --verbose
